### ISSUE TITLE
Cannot install (jupyter installed via MacPorts)

### ISSUE THREAD

**Issue by m7thon** [Jupyter-contrib/jupyter_nbextensions_configurator#15]
I have jupyter installed via MacPorts (which means the main `jupyter` command is `jupyter-3.4`), and did

```
pip install jupyter_nbextensions_configurator --user
```

Now
```
jupyter-3.4 nbextensions_configurator enable --user
```

gives

```
jupyter: 'nbextensions_configurator' is not a Jupyter command
```

Please help.

**Comment by m7thon** [comment]
I was able to complete installation by calling

```
python Library/Python/3.4/lib/python/site-packages/jupyter_nbextensions_configurator/application.py enable
```

**Comment by jcb91** [comment]
Hi @m7thon thanks for reporting this. This issue is essentially caused by jupyter's subcommand-discovery mechanism, which essentially amounts to finding an executable named `jupyter-subcommand` on the path. MacPorts should really have a select command to symlink `jupyter` to the relevant python versioned one, but so far I don't think one exists. If I recall correctly, there was some issue that made it non-trivial. I'd recommend manually symlinking it if possible, to avoid similar issues with other jupyter subcommands.

**Comment by m7thon** [comment]
Thanks. I figured this is likely related to the way MacPorts installs jupyter. However, symlinking or renaming `jupyter-3.4` to `jupyter` does not fix the subcommand discovery (just tried). Some subcommands do work, though, e.g. `jupyter-3.4 notebook`. So things seem more complicated. I won't investigate :-)

**Comment by jcb91** [comment]
> symlinking or renaming `jupyter-3.4` to `jupyter` does not fix the subcommand discovery (just tried)

oh nuts :( Ah well, I'm not sure what's going on then, unless jupyter resolves symlinks before checking the name? Anyway, probably not worth losing sleep over!
