### ISSUE TITLE
error loading nbextensions_configurator

### ISSUE THREAD

**Issue by gaowqspace** [Jupyter-contrib/jupyter_nbextensions_configurator#163]
My jupyter notebook version is 6.5.4, I installed extension with
`conda install -c conda-forge jupyter_nbextensions_configurator`
Then I restart notebook, my Nbextensions page is not completely. And it send me this error message in the bottom:
`[jupyter_nbextensions_configurator] error loading nbextensions_configurator/config_menu/main`

**Comment by devIbtihadj** [comment]
no sulution till now please?
i have the same problem

**Comment by gaowqspace** [comment]
> no sulution till now please? i have the same problem

You can try `pip install jupyterlab==3.0.0 tornado==6.1` and re-install jupyter by:
`pip install jupyter`
`pip install jupyter_contrib_nbextensions`  
`jupyter contrib nbextension install --user`

**Comment by MKLinux22** [comment]
Hi All,

struggeled with the same issue today. It was not a good idea to install nbextensions with conda
`conda install -c conda-forge jupyter_nbextensions_configurator`
because this conda-forge is using older version of jupyter-nbextensions-configurator (0.6.1), which is causing this issue.

The issue can be fixed, by using Anaconda Prompt and install newer version of jupyter-nbextensions-configurator:
`pip install jupyter-nbextensions-configurator==0.6.3`
