### ISSUE TITLE
Unable to use custom template path

### ISSUE THREAD

**Issue by azjps** [Jupyter-contrib/jupyter_nbextensions_configurator#20]
I was trying to set up nbextensions in a directory other than `jupyter_data_dir()`. In my jupyter notebook config I have the following code:

``` python
import os, sys
data_dir = '/home/some_shared_user/.local/share/jupyter/'
sys.path.append(os.path.join(data_dir, 'extensions'))

templates_dir = os.path.join(data_dir, 'templates')
c.NotebookApp.server_extensions = ["nbextensions"]
c.NotebookApp.extra_template_paths = [templates_dir]
c.Exporter.template_path = [templates_dir]
```

This is the resulting config:

``` python
>>> print(c)
{'Exporter':
  {'template_path': ['/home/some_shared_user/.local/share/jupyter/templates']},
   'NotebookApp': {'ip': '...', 'server_extensions': ['nbextensions'],
                   'extra_template_paths': ['/home/some_shared_user/.local/share/jupyter/templates'],
                   'open_browser': False, 'password': 'sha1:...', 'port': 38001
  }
}
```

When launching a jupyter notebook from the `some_shared_user` user, the `/nbextensions` html page loads correctly. However when using the same config on another user (with permissions to read `/home/some_shared_user/.local/share/jupyter/`, but with their `jupyter_data_dir()` unchanged from default), the `/nbextensions` html page can be loaded but the server does not have any of the `/nbextensions/custom/..` css or js etc, so the page is blank. Are there other configs I need to set for this?

**Comment by jcb91** [comment]
yep, the notebook server looks for nbextensions in directories listed in the `NotebookApp`'s `nbextensions_path`, which is a property. To add extra search directories, set the config key `NotebookApp.extra_nbextensions_path` (see [notebook/notebookapp.py#L633-L635](https://github.com/jupyter/notebook/blob/cf7dae8fe5c84e2fee60544e8a94a64b4081ac99/notebook/notebookapp.py#L633-L635)) to a list of string filepaths. In your case, I guess this would be something like

```python
c.NotebookApp.extra_nbextensions_path = ['/home/some_shared_user/.local/share/jupyter/']
```

Note that all of the configuration you have above could be done in json, rather than resorting to a python config file, and that the config extension referred to in the line 

```python
c.NotebookApp.server_extensions = ["nbextensions"]
```

has been spun out of this repo, and is now provided by the standalone [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator).

Hope that helps a little...

**Comment by azjps** [comment]
Cool, after [installing nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/783) with `--sys-prefix` it seems like there's minimal config work that needs to be done :smile: Thanks for the help!

(I've been keeping the configs in python so that its a bit easier for myself to debug and have some simple logic flow.)
