### ISSUE TITLE
UI questions

### ISSUE THREAD

**Issue by juhasch** [Jupyter-contrib/jupyter_nbextensions_configurator#29]
I was looking at the configuration page and had some questions:
* What does the reload button (at the right corner) do?
<img width="793" alt="bildschirmfoto 2017-02-19 um 20 49 34" src="https://cloud.githubusercontent.com/assets/2445216/23105778/f80c34b2-f6e4-11e6-9acb-674459530d3b.png">

* What does the reload/reset button (at the right corner) do ?
<img width="791" alt="bildschirmfoto 2017-02-19 um 20 51 56" src="https://cloud.githubusercontent.com/assets/2445216/23105803/5348a7ac-f6e5-11e6-9126-3e44fbd4501b.png">

* How does the filter work ?
The `section` seems to be useful. I don't understand `tag` and `name` seems to be not very useful, as you have to add any extension by hand. Is there a chance to select several extensions at once by name or by keywords in the description ?

**Comment by jcb91** [comment]
> What does the reload button (at the right corner) do?

The top right one refreshes the list of configurable nbextensions, by making a new call to the JSON handler without reloading the whole page. Perhaps it should have a tooltip of some kind to make this clearer?


> How does the filter work ?

The filter works by looking through a set of tags which are sorted by type, and are created for each nbextension as the list is loaded. Each one has an auto-created `section` tag and `name` tag, plus additional `tag` tags can be added in the configurator yaml declaration files - see e.g.  [config_menu.yaml#L7-L9](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/blob/5940acb7d0894e8b2b7df9b2426305892145d6d7/src/jupyter_nbextensions_configurator/static/nbextensions_configurator/config_menu/config_menu.yaml#L7-L9).

> I don't understand `tag` and `name` seems to be not very useful, as you have to add any extension by hand

The name ones _should_ be created automatically for each nbextension, so that typing any word in the name should make them appear - is that not what's happening for you? The idea behind the tag ones is for them to function essentially as keywords in the way you describe, except that I couldn't think of a way to automatically extract them from the description, so just made them explicitly set for now. I was also thinking they could also be used for pseudo-categories liek the old `usability` and `styling` directories. However, I haven't made any PRs to add relevant tags to the yaml files in https://github.com/ipython-contrib/jupyter_contrib_nbextensions, so you're right, they're not very useful right now...

**Comment by jcb91** [comment]
sorry, missed that there were two reload questions:

> What does the reload/reset button (at the right corner) do ?

The one on the parameters section header effectively resets all the parameters to their defaults. It actually removes all the parameter tags from the relevant config file, so that the nbextension should go back to using the defaults from the javascript implementation. This is because the `default` key in the yaml sometimes isn't exactly the same as in the js implementation.

**Comment by jcb91** [comment]
Does any of that make sense? Perhaps it would be worth updating the docs or adding some tooltips or other explanatory text to the page?

**Comment by juhasch** [comment]
Thanks for the explanation. Makes sense.
I was trying to explain what the configurator does and so I came up with these questions.

The reload button is not shown in the screenshot. I think it would be sufficient it there is a toolbar explaining it reloads the extensions list.

For the reset, maybe it would be `reset parameters to default values`.

With the filter, I think it makes sense. I was more asking myself if it is really helpful like this. Personally, if I know the name of the extension, I don't need to filter. Otherwise I am looking for something, then I am probably looking for a keyword in the description. As we have online documentation on readthedocs, I guess there is no need to overdesign things. Maybe a link to the documentation...

**Comment by jcb91** [comment]
Right, I'll add some tooltips.

>  Personally, if I know the name of the extension, I don't need to filter

True in most cases, I guess it's only useful if you can remember one word in the name, but not the rest, but that seems pretty unlikely on reflection. Perhaps it'd be best to remove the name tags in favour of better keyword tags.

> Otherwise I am looking for something, then I am probably looking for a keyword in the description

True, the keywords are/would be the main useful feature, and they're not properly implemented yet. I guess it would also be possible to take words from the description to auto-create tags, that sounds a pretty useful idea. I'll have a think...

**Comment by juhasch** [comment]
I just tried the reload button: Does not work for me. Reloading the page using CTRL-R shows my added/removed extension.

**Comment by jcb91** [comment]
To be fair, I haven't done much testing, so it may not actually work correctly, or at all. I'll have to investigate...

**Comment by jcb91** [comment]
Ha, yes, on further investigation, I added the button, but failed to actually connect it to a callback...

**Comment by jcb91** [comment]
So, I think I've addressed these issues in #31 - let me know if you get a chance to take a look :smile:

**Comment by juhasch** [comment]
- [x]  reload button working
- [x]  tooltip for reload button 
- [x]  tooltip for parameter reset button 
- [ ]  easy keyword searching

**Comment by jcb91** [comment]
@juhasch I've had a go at implementing name & description text searching in #34 - is that the kind of thing you meant? I guess ideally it would also search readmes, but they're currently only lazy-loaded when needed, and it could really up traffic to load all of them every time the page loads, so I haven't bothered for now...

**Comment by juhasch** [comment]
Cool, this is really nice! 
I don't think parsing the readme file is needed. That would be overkill, IMO.

**Comment by juhasch** [comment]
I think we can close this now 🥇
