### ISSUE TITLE
incompatibility problem

### ISSUE THREAD

**Issue by sw007** [Jupyter-contrib/jupyter_nbextensions_configurator#30]
![image](https://cloud.githubusercontent.com/assets/12022137/23245933/380a498a-f9cb-11e6-9a5e-cde19ce4e87f.png)
I am running into incompatibility problems with code-folding. Not sure if I am missing something.
I installed ipython and etc. fairly recently via anaconda, so it should be up to date. I installed the extension configurator via conda as well. When I run `jupyter nbextension enable codefolding` in terminal, I get back the following:
![image](https://cloud.githubusercontent.com/assets/12022137/23246019/b240b57c-f9cb-11e6-9985-bc2c124d88fe.png)
Also, in jupyter notebook, 
![image](https://cloud.githubusercontent.com/assets/12022137/23246059/f65704b4-f9cb-11e6-9609-06c21629ab31.png)

Any help is greatly appreciated.

**Comment by jcb91** [comment]
So it looks like you haven't actually _installed_ the nbextension, just _enabled_ it (i.e. told the notebook to load it, but not provided the files to load). We don't have a simple way to install just codefolding without the rest of the collection in this repo. If you really want to do that, it is technically possible, but a bit of a fiddle, and you'll have to download the whole repo anyway. Given you're using conda, the simplest method would be to install the whole collection

    conda install jupyter_contrib_nbextensions

And that should be enough (since you've already done the enabling of codefolding). The other nbextensions will be installed, but not activated by default.

If you've installed via pip from the repo (e.g. to get updates which haven't yet been in a packaged release), then you'll need to run the second step of the installation instructions in the main readme, which is essentially

    jupyter contrib nbextensions install --sys-prefix

(Again, I specify the ssy-prefix because you seem to be using conda. The command should be run from the conda env which will run your notebook _server_).

Does that make sense?

**Comment by jcb91** [comment]
bleagh, sorry, didn't realise that you'd posted this on _this_ repo, not the jupyter_contrib_nbextensions one. How did you install codefolding?

**Comment by jcb91** [comment]
@sw007 any further details on this?

**Comment by jcb91** [comment]
closing due to lack of further details, and since this belongs on https://github.com/ipython-contrib/jupyter_contrib_nbextensions anyway, really
