### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by parmentelat** [Jupyter-contrib/jupyter_nbextensions_configurator#49]
Hey there
Thanks for the configurator, it's very convenient

I just installed a new mac computer, and am running into an issue when setting up the tool; 
I did pip install + `jupyter nbextensions_configurator enable`
but instead of the usual mostly white configurator (that was working just fine on the previous mac omputer that I was using) I am seeing all extensions as grayed out, and I can't configure them, see attached

Clearly I screwed something up but I can't spot what that was.

Thanks again

![screen shot 2017-11-03 at 13 01 22](https://user-images.githubusercontent.com/4519227/32372918-2f88f5ca-c097-11e7-8bfa-8929cb5ccf1a.png)

**Comment by jcb91** [comment]
> Thanks for the configurator, it's very convenient

Thanks, glad you like it 😊

So it seems from the warning that splitcell doesn't have a yaml file. I suspect this is because you've copied a config file from another installation somewhere, but in the new installation you've installed the  configurator, but not the `jupyter_contrib_nbextensions` package (or at least the JavaScript bits from it), which provides most of the JavaScript nbextensions listed. The nbextensions you're seeing here are listed because they've been explicitly enabled or disabled in that pre-existing config file. If you just want to remove them entirely, I think you should be able to disable them, and then use the 'forget' button to remove the reference in the config file. To enable them, you'll need to install the contrib package, but there's a couple also which don't come with that package (jupyter-js-widgets, livereveal, rise, maybe others), which may also need installing separately (although in these cases, the packages may not provide yaml files at all, so they may not be configurable beyond enable/disable).

That's was a bit long-winded, I hope it makes at least _some_ sense?

In brief, I think you need to do a 

    pip install jupyter_contrib_nbextensions
    jupyter contrib nbextension install

Or, if you're using conda, you can do it in a single line with

    conda install jupyter_contrib_nbextensions

**Comment by parmentelat** [comment]
you're right, I just needed to do `jupyter contrib nbextension install`; thanks a lot :)

I've been puzzled by your text when you mentioned rise and livereveal. 
first because these 2 things are the same, aren't they ? 
second, it turns out I've been contributing a bit to RISE - that's how I know it used to be called livereveal, and I was wondering where I could find documentation on this yaml file ?
we've just added more configurablity in RISE, and the next step would reasonably be to open up the settings to something like configurator, so...

thanks again

**Comment by jcb91** [comment]
Great, glad you got it sorted :)

> I've been puzzled by your text when you mentioned rise and livereveal.
> first because these 2 things are the same, aren't they ?
> second, it turns out I've been contributing a bit to RISE - that's how I know it used to be called livereveal, 

They might be the same thing, I'm not sure :laughing:. My guess as to what's happened is you've used the old name/require path (`livereveal/main`), then when switching to the new one, disabled it. However, disabling the nbextension just sets its value to `false` in the `load_extensions` dict in the `notebook.json` config file, so the configurator still lists it (because, you know, you might want to re-enable it, it has no way of knowing). This is the kind of situation that the 'forget' button is for - it will completely remove the relevant key from the `load_extensions` dict, so the configurator won't show it any more.

> I was wondering where I could find documentation on this yaml file ?
> we've just added more configurablity in RISE, and the next step would reasonably be to open up the settings to something like configurator, so...

Ah, that'd be great :smile: :+1: I think the only documentation that currently exists is [in the README for this repo](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/blob/c48a0b579ba82de467e8e4bbb207882d83864637/README.md#yaml-file-format) :worried: (you should also be able to read this from the 'more information' link in the title of a local server's `/nbextensions/` page). The yaml file needs to end up somewhere in the nbextensions path, and reference the main nbextension javascript file correctly. The simplest way (IMO) is to just stick it in the same directory as the main javascript file, so that it gets installed with that automatically.

The configurator currently constructs most html5 inputs ok just by stating the`input_type` key for parameters (e.g. `input_type: url`), but some have more extensive support than others. One quirk is that any default values for colors need to be specified as 6-char hex codes, because for some reason the 3-char version doesn't set the control correctly (e.g. use `#FFEEEE` rather than `#FEE`). I haven't implemented any kind of select-list enum kind of thing, or a json-object type field (similar to editing notebook metadata), which might be useful in some circumstances. If you'd like those, drop me a line & I can give it a go. Equally, any questions with implementing your RISE config, let me know :+1:

**Comment by parmentelat** [comment]
Thanks a lot for the detailed answer, this is quite interesting an opportunity for us I would think :)

**Comment by parmentelat** [comment]
as an epilogue:

* I actually screwed up a little earlier, I had not realized that I had copied over my `.jupyter` from the previous box - actually, I knew I had copied it over, but had not realized it would also carry remainings of my previous configurations; so that was why I mentioned livereveal and rise in the first place, I tohught they had come with `jupyter_nbextensions_configurator`; so with your help I have this nice and clean now

* second, thanks for the pointer on your yaml format; from a quick browsing it looks like this does not handle keyboard shortcuts, I take it users would use the more generic 'Edit Keyboard Shortcuts', right ?

**Comment by jcb91** [comment]
> so with your help I have this nice and clean now

Great :)

>  it looks like this does not handle keyboard shortcuts, I take it users would use the more generic 'Edit Keyboard Shortcuts', right ?

Sort of. It supports a control to capture a keyboard shortcut using the `hotkey` input type, storing it in a text form suitable for use with Jupyter's keyboard manager. You still need to handle binding the shortcut as part of the nbextension code. See for example the yaml declarations of editable keyboard shortcuts in [collapsible_headings/collapsible_headings.yaml#L61-L88](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/5646a5b75467830e7fef739a42d6a7e88ac9f1a5/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/collapsible_headings.yaml#L61-L88) and the accompanying code to bind actions to the shortcuts in [collapsible_headings/main.js#L882-L890](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/5646a5b75467830e7fef739a42d6a7e88ac9f1a5/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/main.js#L882-L890). I'm not sure how well this will play with the generic keyboard shortcut editor, I haven't looked into how it works...

**Comment by parmentelat** [comment]
Understood, thank you Josh

**Comment by parmentelat** [comment]
thanks a lot, I'm closing this as we are now ready to use the configurator

**Comment by LFK01** [comment]
Hi everyone,
I'm nowhere near as expert as you guys above but I've got the same problem of this issue: installed nbextensions on a Mac following the steps in the guide but it says that all the extensions are not compatible.

I tried to redo the steps above:
`pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install`
I tried also:
`pip3 install jupyter_contrib_nbextensions
jupyter contrib nbextension install`
as it could change something I don't know but it doesn't work either.

I'm running:
`python 3.8.2
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5`
If it is necessary to know anything else about my environment I'm glad to inform you about anything else.
Thank you
