### ISSUE TITLE
Only two extensions available after installing

### ISSUE THREAD

**Issue by MaxGhenis** [Jupyter-contrib/jupyter_nbextensions_configurator#65]
I'm on Ubuntu (ChromeOS via crouton) and installed via `conda` after a fresh install of `conda`, Jupyter, and IRkernel. But I'm only seeing two available extensions.
![screenshot 2018-04-15 at 16 28 04](https://user-images.githubusercontent.com/6076111/38784655-fd31a65e-40c9-11e8-9773-0543b693ab62.png)

[Here's](https://gist.github.com/MaxGhenis/2a9959a351d00b8bb31895c3eaca0afd) some of my installation output, where I tried restarting the Jupyter kernel a couple times after updating conda.

**Comment by jcb91** [comment]
So the configurator itself provides the two nbextensions you're seeing I'm the interface. Just to double-check, you also installed some other nbextensions which you're hoping to see as well? Perhaps the jupyter_contrib_nbextensions collection? If you're after that, and they're not showing up, I assume you installed the contrib collection with conda as well, in which case this is presumably caused by a failure in the conda post-link script, which is supposed to copy the js & CSS from the python site-packages directory into the jupyter sys-prefix (env-specific) data directory.

To fix, you could try conda uninstall and then reinstall of the contrib nbextensions package. Alternatively, if it's definitely installed (or if you installed it using pip rather than conda), you could try to re-run the sommand to copy js & css. With the relevant conda environment activated (that's the one from which you will run `jupyter notebook`, not any environment you may you for kernels), you can use

    jupyter contrib nbextension install --sys-prefix

To copy everything over. Add the `--debug` flag for extra output (a lot). Since you're on *nix, you could also add the `--symlink` flag if you fancy.

If you could reply with anything you discover, that'd be great. This kind of issue seems to keep coming up, but so far I haven't seen any obvious cause...

**Comment by jcb91** [comment]
Apologies, after reading the output in the gist, it looks like the problem here is (possibly) just some mixup of the two packages `jupyter_nbextensions_configurator` (this one, which provides config UIs for nbextensions, but doesn't really provide any nbextensions beyond its own interface), and [`jupyter_contrib_nbextensions`](https://github.com/ipython-contrib/jupyter_contrib_nbextensions), which provides a collection of a whole bunch of nbextensions, and uses this package as a dependency to provide a neat way to configure them. Potentially, your fix may be as simple as

    conda install -c conda-forge jupyter_contrib_nbextensions

Apologies for the confusion, it's far from obvious to people looking at this for the first time!

**Comment by MaxGhenis** [comment]
Ah sorry, yes I thought this also installed the extensions. This worked. Thank you!

    conda install -c conda-forge jupyter_contrib_nbextensions

**Comment by pepperamy** [comment]
I got the same problem. I did `conda install -c conda-forge jupyter_nbextensions_configurator` and then `conda install -c conda-forge jupyter_contrib_nbextensions`. But I only got a few extensions.

**Comment by ChenglongMa** [comment]
I installed the package via `conda install -c conda-forge jupyter_contrib_nbextensions`, but just saw a few extensions.

Rerunning the following command manually solves the problem.

```bash
jupyter contrib nbextension install --sys-prefix
````
